volumes:
  n8n_data:
    external: true

networks:
  reverse-proxy:
    external: true

services:
  n8n:
    container_name: n8n  
    image: n8nio/n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=sqlite
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=YourSecurePassword
      - N8N_RUNNERS_ENABLED=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_PUSH_BACKEND=websocket
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - reverse-proxy      