FROM ubuntu:22.04
RUN echo 'APT::Install-Suggests "0";' >> /etc/apt/apt.conf.d/00-docker
RUN echo 'APT::Install-Recommends "0";' >> /etc/apt/apt.conf.d/00-docker

RUN DEBIAN_FRONTEND=noninteractive 
RUN apt update
RUN apt install -y gawk wget git-core diffstat unzip texinfo \
    gcc-multilib build-essential chrpath socat file cpio python3 \
    python3-pip python3-pexpect xz-utils debianutils iputils-ping \
    libsdl1.2-dev xterm tar locales net-tools rsync sudo vim curl zstd \
    liblz4-tool libssl-dev bc lzop libgnutls28-dev efitools git-lfs

RUN rm /bin/sh && ln -s bash /bin/sh

ARG USER
RUN echo "root ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/root && \
    chmod 0440 /etc/sudoers.d/root

# Install dockerize for config files
RUN curl -sfL $(curl -s https://api.github.com/repos/powerman/dockerize/releases/latest \
  | grep -i /dockerize-$(uname -s)-$(uname -m)\" | cut -d\" -f4) \
  | install /dev/stdin /usr/local/bin/dockerize

USER root