networks:
  reverse-proxy:
    external: true

volumes:
  coolify-data:
    external: true
  coolify-postgres:
    external: true

services:
  coolify:
    image: ghcr.io/coollabsio/coolify:latest
    container_name: coolify
    ports:
      - "8080:8080"
    volumes:
      - coolify-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://coolify:coolify@coolify-db:5432/coolify
      REDIS_HOST: coolify-redis
      APP_KEY: "get it by: php artisan key:generate"
    networks:
      - reverse-proxy

  postgres:
    image: postgres:15-alpine
    container_name: coolify-db
    restart: always
    environment:
      POSTGRES_USER: coolify
      POSTGRES_PASSWORD: coolify
      POSTGRES_DB: coolify
    volumes:
      - coolify-postgres:/var/lib/postgresql/data
    networks:
      - reverse-proxy

  redis:
    image: redis:7-alpine
    container_name: coolify-redis
    restart: always
    networks:
      - reverse-proxy
