networks:
  reverse-proxy:
    external: true

volumes:
  opencloud_data:
    external: true
  opencloud_config:
    external: true

services:
  opencloud:
    container_name: opencloud
    hostname: opencloud
    image: opencloudeu/opencloud-rolling:latest
    entrypoint:
      - /bin/sh
    networks:
      - reverse-proxy
    command: ["-c", "opencloud init || true; opencloud server"]
    environment:
      # PROXY_HTTP_ADDR: "0.0.0.0"
      # change to the public domain name of your OpenCloud instance with protocol and port
      OC_URL: https://opencloud.luigimicco.it
      OC_LOG_LEVEL: info
      # uncomment if you do not want use SSL between the reverse proxy and OpenCloud
      # PROXY_TLS: "false"
      # INSECURE: needed if OpenCloud is using self generated certificates
      OC_INSECURE: "true"
      # basic auth (not recommended, but needed for eg. WebDav clients that do not support OpenID Connect)
      PROXY_ENABLE_BASIC_AUTH: "false"
      # admin user password
      IDM_ADMIN_PASSWORD: "admin" # this overrides the admin password from the configuration file
      # demo users
      # IDM_CREATE_DEMO_USERS: "true"    
    ports:
      - 9200:9200
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro"
      - opencloud_data:/var/lib/opencloud
      - opencloud_config:/etc/opencloud
      # - opencloud_apps:/var/lib/opencloud/web/assets/apps
      # - "certs:/certs"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    logging:
      driver: local
    restart: unless-stopped
    
    # depends_on:
    #   drawio-init:
    #     condition: service_completed_successfully
    #   externalsites-init:
    #     condition: service_completed_successfully   
    #   importer-init:
    #     condition: service_completed_successfully  
    #   jsonviewer-init:
    #     condition: service_completed_successfully   
    #   unzip-init:
    #     condition: service_completed_successfully

  # drawio-init:
  #   image: opencloudeu/web-extensions:draw-io-1.0.0
  #   user: root
  #   volumes:
  #     - opencloud_apps:/apps
  #   entrypoint:
  #     - /bin/sh
  #   command: ["-c", "cp -R /usr/share/nginx/html/draw-io/ /apps"]

  # externalsites-init:
  #   image: opencloudeu/web-extensions:external-sites-1.0.0
  #   user: root
  #   volumes:
  #     - opencloud_apps:/apps
  #   entrypoint:
  #     - /bin/sh
  #   command: ["-c", "cp -R /usr/share/nginx/html/external-sites/ /apps"]    

  # importer-init:
  #   image: opencloudeu/web-extensions:importer-1.0.0
  #   user: root
  #   volumes:
  #     - opencloud_apps:/apps
  #   entrypoint:
  #     - /bin/sh
  #   command: [ "-c", "cp -R /usr/share/nginx/html/importer/ /apps" ]    

  # jsonviewer-init:
  #   image: opencloudeu/web-extensions:json-viewer-1.0.0
  #   user: root
  #   volumes:
  #     - opencloud_apps:/apps
  #   entrypoint:
  #     - /bin/sh
  #   command: ["-c", "cp -R /usr/share/nginx/html/json-viewer/ /apps"]

  # unzip-init:
  #   image: opencloudeu/web-extensions:unzip-1.0.2
  #   user: root
  #   volumes:
  #     - opencloud_apps:/apps
  #   entrypoint:
  #     - /bin/sh
  #   command: ["-c", "cp -R /usr/share/nginx/html/unzip/ /apps"]    