networks:
  reverse-proxy:
    external: true

volumes:
  opencloud_data:
    external: true
  opencloud_config:
    external: true
  opencloud_apps:
    external: true

services:
  opencloud:
    container_name: opencloud
    hostname: opencloud
    image: opencloudeu/opencloud-rolling:latest
    entrypoint:
      - /bin/sh
    networks:
      - reverse-proxy
    command: ["-c", "opencloud init || true; opencloud server"]
    environment:
      # PROXY_HTTP_ADDR: "0.0.0.0"
      # change to the public domain name of your OpenCloud instance with protocol and port
      OC_URL: https://opencloud.luigimicco.it
      OC_LOG_LEVEL: info
      # uncomment if you do not want use SSL between the reverse proxy and OpenCloud
      # PROXY_TLS: "false"
      # INSECURE: needed if OpenCloud is using self generated certificates
      OC_INSECURE: "true"
      # basic auth (not recommended, but needed for eg. WebDav clients that do not support OpenID Connect)
      PROXY_ENABLE_BASIC_AUTH: "false"
      # admin user password
      IDM_ADMIN_PASSWORD: "admin" # this overrides the admin password from the configuration file
      # demo users
      # IDM_CREATE_DEMO_USERS: "true"    

      # make collabora the secure view app
      FRONTEND_APP_HANDLER_SECURE_VIEW_APP_ADDR: eu.opencloud.api.collaboration.CollaboraOnline
      GRAPH_AVAILABLE_ROLES: "b1e2218d-eef8-4d4c-b82d-0f1a1b48f3b5,a8d5fe5e-96e3-418d-825b-534dbdf22b99,fb6c3e19-e378-47e5-b277-9732f9de6e21,58c63c02-1d89-4572-916a-870abc5a1b7d,2d00ce52-1fc2-4dbc-8b95-a73b73395f5a,1c996275-f1c9-4e71-abdf-a42f6495e960,312c0871-5ef7-4b3a-85b6-0e4074c64049,aa97fe03-7980-45ac-9e50-b325749fd7e6"

    ports:
      - 9200:9200
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro"
      - opencloud_data:/var/lib/opencloud
      - opencloud_config:/etc/opencloud
      - opencloud_apps:/var/lib/opencloud/web/assets/apps

    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    logging:
      driver: local
    restart: unless-stopped
    
    depends_on:
      drawio-init:
        condition: service_completed_successfully
      externalsites-init:
        condition: service_completed_successfully   
      importer-init:
        condition: service_completed_successfully  
      jsonviewer-init:
        condition: service_completed_successfully   
      unzip-init:
        condition: service_completed_successfully

  collaboration:
    image: opencloudeu/opencloud-rolling:latest
    networks:
      - reverse-proxy
    depends_on:
      opencloud:
        condition: service_started
      collabora:
        condition: service_healthy
    entrypoint:
      - /bin/sh
    command: [ "-c", "opencloud collaboration server" ]
    environment:
      COLLABORATION_GRPC_ADDR: 0.0.0.0:9301
      COLLABORATION_HTTP_ADDR: 0.0.0.0:9300
      MICRO_REGISTRY: "nats-js-kv"
      MICRO_REGISTRY_ADDRESS: "opencloud:9233"
      COLLABORATION_WOPI_SRC: https://wopiserver.luigimicco.it
      COLLABORATION_APP_NAME: "CollaboraOnline"
      COLLABORATION_APP_PRODUCT: "Collabora"
      COLLABORATION_APP_ADDR: https://collabora.luigimicco.it
      COLLABORATION_APP_ICON: https://collabora.luigimicco.it/favicon.ico
      COLLABORATION_APP_INSECURE: "true"
      COLLABORATION_CS3API_DATAGATEWAY_INSECURE: "true"
      COLLABORATION_LOG_LEVEL: info
      OC_URL: https://opencloud.luigimicco.it
    volumes:
      # configure the .env file to use own paths instead of docker internal volumes
      - opencloud_config:/etc/opencloud
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    logging:
      driver: local
    restart: unless-stopped

  collabora:
    image: collabora/code:25.04.2.1.1
    # release notes: https://www.collaboraonline.com/release-notes/
    networks:
      opencloud-net:
    environment:
      aliasgroup1: https://wopiserver.luigimicco.it:443
      DONT_GEN_SSL_CERT: "YES"
      extra_params: |
        --o:ssl.enable=true \
        --o:ssl.ssl_verification=true \
        --o:ssl.termination=true \
        --o:welcome.enable=false \
        --o:net.frame_ancestors=opencloud.luigimicco.it
      username: admin
      password: admin
    cap_add:
      - MKNOD
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    logging:
      driver: local
    restart: unless-stopped
    entrypoint: ['/bin/bash', '-c']
    command: ['coolconfig generate-proof-key && /start-collabora-online.sh']
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 3<>/dev/tcp/127.0.0.1/9980 && echo -e 'GET /hosting/discovery HTTP/1.1\r\nHost: localhost:9980\r\n\r\n' >&3 && head -n 1 <&3 | grep '200 OK'"]


  drawio-init:
    image: opencloudeu/web-extensions:draw-io-1.0.0
    user: root
    volumes:
      - opencloud_apps:/apps
    entrypoint:
      - /bin/sh
    command: ["-c", "cp -R /usr/share/nginx/html/draw-io/ /apps"]

  externalsites-init:
    image: opencloudeu/web-extensions:external-sites-1.0.0
    user: root
    volumes:
      - opencloud_apps:/apps
    entrypoint:
      - /bin/sh
    command: ["-c", "cp -R /usr/share/nginx/html/external-sites/ /apps"]    

  importer-init:
    image: opencloudeu/web-extensions:importer-1.0.0
    user: root
    volumes:
      - opencloud_apps:/apps
    entrypoint:
      - /bin/sh
    command: [ "-c", "cp -R /usr/share/nginx/html/importer/ /apps" ]    

  jsonviewer-init:
    image: opencloudeu/web-extensions:json-viewer-1.0.0
    user: root
    volumes:
      - opencloud_apps:/apps
    entrypoint:
      - /bin/sh
    command: ["-c", "cp -R /usr/share/nginx/html/json-viewer/ /apps"]

  unzip-init:
    image: opencloudeu/web-extensions:unzip-1.0.2
    user: root
    volumes:
      - opencloud_apps:/apps
    entrypoint:
      - /bin/sh
    command: ["-c", "cp -R /usr/share/nginx/html/unzip/ /apps"]    