volumes:
  nextcloud_aio_mastercontainer:
    external: true

networks:
  reverse-proxy:
    external: true

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    hostname: nextcloud
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 6789:8080 # change the port on the left side if it's already in use on your host system.
    environment:
      - APACHE_PORT=6789
      - APACHE_IP_BINDING=0.0.0.0
    labels:
      - "com.centurylinklabs.watchtower.enable=true"  
    networks:
      - reverse-proxy       
    
