volumes:
  nextcloud_data:
    external: true

networks:
  reverse-proxy:
    external: true

services:
  aio:
    image: nextcloud/all-in-one:latest
    init: true
    restart: unless-stopped
    hostname: nextcloud
    container_name: nextcloud
    ports:
      - 11000:11000
    volumes:
      - nextcloud_data:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "com.centurylinklabs.watchtower.enable=true"      
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=127.0.0.1
    networks:
      - reverse-proxy
