volumes:
  nextcloud_aio_mastercontainer:
    external: true

networks:
  reverse-proxy:
    external: true

services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    restart: always
    ports:
      - '8080:8080'
      - '4443:443'
    environment:
      - SKIP_DOMAIN_VALIDATION=true
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=89.168.31.129
      - NEXTCLOUD_DATADIR=/mnt/data-nextcloud
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "com.centurylinklabs.watchtower.enable=true"  
    networks:
      - reverse-proxy       
    
