volumes:
  nextcloud_aio_mastercontainer:
    external: true

networks:
  reverse-proxy:
    external: true

services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    init: true
    restart: unless-stopped
#    network_mode: host
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/storage/nextcloud/data:/mnt/ncdata
    environment:
      SKIP_DOMAIN_VALIDATION: true
      NEXTCLOUD_DATADIR: /srv/storage/nextcloud/data
      NEXTCLOUD_ADMIN_PASSWORD: ZmhV5cbvB3aPiK
      NEXTCLOUD_ADMIN_USER: admin
      APACHE_PORT: 11000
    ports:
      - 8080:8080
    labels:
      - "com.centurylinklabs.watchtower.enable=true"         
    
