volumes:
  nextcloud_aio_mastercontainer:
    external: true

networks:
  reverse-proxy:
    external: true

services:
  aio:
    image: nextcloud/all-in-one:latest
    init: true
    restart: unless-stopped
    hostname: nextcloud-aio-mastercontainer
    container_name: nextcloud-aio-mastercontainer
    ports:
      - 11000:11000
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "com.centurylinklabs.watchtower.enable=true"      
    networks:
      - reverse-proxy
