FROM ubuntu:22.04
RUN echo 'APT::Install-Suggests "0";' >> /etc/apt/apt.conf.d/00-docker
RUN echo 'APT::Install-Recommends "0";' >> /etc/apt/apt.conf.d/00-docker

RUN DEBIAN_FRONTEND=noninteractive 
RUN apt update \
  && apt upgrade -y \
  && apt install -y --no-install-recommends \
    ca-certificates \
    curl \
    htop \
    iotop \
    rsync \
    tar \
    vim \
    unzip \
#    systemctl \
    sudo \
#    systemd \
#    ufw \
    openssh-server \
  && apt clean all \
  && apt autoremove

# Install dockerize for config files
RUN curl -sfL $(curl -s https://api.github.com/repos/powerman/dockerize/releases/latest \
  | grep -i /dockerize-$(uname -s)-$(uname -m)\" | cut -d\" -f4) \
  | install /dev/stdin /usr/local/bin/dockerize

RUN sudo systemctl enable ssh
# RUN sudo systemctl start ssh

USER root